(() => {
  const canvas = document.querySelector('#game');
  const ctx = canvas.getContext('2d');
  if (matchMedia('(max-width: 650px), (pointer: coarse)').matches) canvas.height = 792;
  const W = canvas.width, H = canvas.height, cols = 4, rows = 3, roomW = 264, roomH = 198;
  const keys = new Set(), mouse = { x: W / 2, y: H / 2 }, stick = { x: 0, y: 0, id: null };
  const ui = Object.fromEntries(['stageStatus','hp','mana','skill','hpText','manaText','skillText','heroSelect','boons','choices','gameover','score','resultTitle','resultSub','pauseMenu','pauseButton','weapons'].map(id => [id, document.querySelector(`#${id}`)]));
  ui.weapons = [...document.querySelectorAll('[data-weapon]')]; ctx.imageSmoothingEnabled = false;
  const img = src => { const i = new Image(); i.src = src; return i; };
  const frames = folder => [8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60].map(n => img(`assets/effects/wills_pixel_explosions_sample/${folder}/PNG/frame${String(n).padStart(4, '0')}.png`));
  const sprites = { hero: img('kenney_tinyDungeon/Tiles/tile_0099.png'), melee: img('kenney_tinyDungeon/Tiles/tile_0096.png'), ranged: img('kenney_tinyDungeon/Tiles/tile_0100.png'), rock: img('kenney_tinyDungeon/Tiles/tile_0075.png'), healthPotion: img('kenney_tinyDungeon/Tiles/tile_0129.png'), manaPotion: img('kenney_tinyDungeon/Tiles/tile_0130.png'), burst: frames('round_explosion'), vortex: frames('round_vortex'), attack: { punch: img('assets/effects/sangoro-attack-vfx/PunchImp1.png'), slash: img('assets/effects/sangoro-attack-vfx/Hslash1.png'), spell: img('assets/effects/sangoro-attack-vfx/VslashSmall1.png'), arrow: img('assets/effects/sangoro-attack-vfx/vSlash1.png') } };
  const heroes = { brawler: { weapon: 'fist', damage: 34, range: 72, speed: 270, skillName: '雷霆震地', skillCd: 5000 }, swordsman: { weapon: 'sword', damage: 30, range: 108, speed: 252, skillName: '月牙連斬', skillCd: 4200 }, mage: { weapon: 'staff', damage: 25, range: 90, speed: 240, skillName: '星界風暴', skillCd: 6200 }, ranger: { weapon: 'bow', damage: 27, range: 84, speed: 278, skillName: '箭雨齊射', skillCd: 4500 } };
  const dirs = [{ key: 'n', dx: 0, dy: -1, opposite: 's' }, { key: 'e', dx: 1, dy: 0, opposite: 'w' }, { key: 's', dx: 0, dy: 1, opposite: 'n' }, { key: 'w', dx: -1, dy: 0, opposite: 'e' }];
  const boonPool = [
    ['熾耀耀擊', '普通攻擊傷害 +40%，攻擊範圍 +18%。', p => { p.damage *= 1.4; p.range *= 1.18; }], ['日輪法陣', '法陣範圍 +30%，每秒傷害提高。', p => { p.castRadius *= 1.3; p.castDamage += 10; }], ['炫光奔襲', '移動速度 +15%，衝刺冷卻縮短。', p => { p.speed *= 1.15; p.dashCd *= .7; }], ['月桂護佑', '最大生命 +35，立即回復生命。', p => { p.maxHp += 35; p.hp = Math.min(p.maxHp, p.hp + 35); }], ['星火回響', '每次普通攻擊額外回復 2 點魔力，施法消耗 -4。', p => { p.attackMana += 2; p.castCost = Math.max(6, p.castCost - 4); }], ['靈魂收割', '擊殺敵人時回復 5 點生命。', p => p.harvest = true]
  ];
  let player, maze, room, current, enemies, rocks, pickups, fx, paused, last = 0, clearedAt = 0, boonPending = false, runDone = false;
  const clamp = (v, min, max) => Math.max(min, Math.min(max, v)); const d = (a, b) => Math.hypot(a.x - b.x, a.y - b.y); const id = (x, y) => `${x},${y}`;
  function newPlayer(hero) { return { x: W / 2, y: H / 2, r: 16, hp: 100, maxHp: 100, mana: 100, maxMana: 100, speed: 255, damage: 28, range: 72, weapon: 'fist', facing: 0, attackReady: 0, dashReady: 0, dashUntil: 0, dashCd: 650, skillReady: 0, invuln: 0, manaRegen: 0, attackMana: 3, castCost: 20, castRadius: 95, castDamage: 17, harvest: false, vip: false, hero, ...heroes[hero] }; }
  function buildMaze() {
    maze = new Map(); for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) maze.set(id(x, y), { x, y, doors: {}, seen: false, cleared: false, final: false, visited: false });
    const start = maze.get(id(0, 0)); start.visited = true; const stack = [start];
    while (stack.length) { const cell = stack.at(-1), options = dirs.map(dir => ({ dir, cell: maze.get(id(cell.x + dir.dx, cell.y + dir.dy)) })).filter(o => o.cell && !o.cell.visited); if (!options.length) { stack.pop(); continue; } const next = options[Math.floor(Math.random() * options.length)]; cell.doors[next.dir.key] = true; next.cell.doors[next.dir.opposite] = true; next.cell.visited = true; stack.push(next.cell); }
    maze.forEach(c => delete c.visited); let farthest = start, queue = [[start, 0]], done = new Set([id(0, 0)]); while (queue.length) { const [cell, steps] = queue.shift(); if (steps > (farthest.steps || 0)) { farthest = cell; farthest.steps = steps; } dirs.filter(dir => cell.doors[dir.key]).forEach(dir => { const n = maze.get(id(cell.x + dir.dx, cell.y + dir.dy)); if (!done.has(id(n.x, n.y))) { done.add(id(n.x, n.y)); queue.push([n, steps + 1]); } }); } farthest.final = true; start.cleared = true;
  }
  function terrain() { rocks = []; for (let i = 0; i < 3 + Math.floor(Math.random() * 3); i++) { const p = { x: 130 + Math.random() * (W - 260), y: 105 + Math.random() * (H - 210), r: 24 + Math.random() * 16 }; if (d(p, player) > 150 && !rocks.some(r => d(r, p) < r.r + p.r + 50)) rocks.push(p); } }
  function makeEnemy(type, index) { const side = index % 4, pos = [{ x: 80, y: 90 + Math.random() * (H - 180) }, { x: W - 80, y: 90 + Math.random() * (H - 180) }, { x: 100 + Math.random() * (W - 200), y: 80 }, { x: 100 + Math.random() * (W - 200), y: H - 80 }][side]; const boss = type === 'boss'; const scale = boss ? 2.25 : 1; return { ...pos, type, r: (boss ? 30 : 17) * scale / (boss ? 1 : 1), hp: (boss ? 720 : type === 'ranged' ? 85 : 110), maxHp: (boss ? 720 : type === 'ranged' ? 85 : 110), speed: boss ? 72 : type === 'ranged' ? 75 : 112, damage: boss ? 30 : type === 'ranged' ? 12 : 16, ready: 0, skill: performance.now() + 2800, charge: 0, hit: 0, dead: false }; }
  function enter(cell, entry) { current = cell; room = cell; room.seen = true; player.x = entry === 'w' ? 46 : entry === 'e' ? W - 46 : W / 2; player.y = entry === 'n' ? 46 : entry === 's' ? H - 46 : H / 2; terrain(); fx = []; pickups = []; enemies = []; clearedAt = 0; boonPending = false; if (!room.cleared) { const count = room.final ? 1 : 3 + Math.floor(Math.random() * 3); for (let i = 0; i < count; i++) enemies.push(makeEnemy(room.final ? 'boss' : Math.random() < .32 ? 'ranged' : 'melee', i)); } }
  function start(hero) { player = newPlayer(hero); buildMaze(); paused = false; runDone = false; enter(maze.get(id(0, 0))); updateHUD(); }
  function nextRoom(dir) { if (!room.cleared || !room.doors[dir.key]) return; const cell = maze.get(id(room.x + dir.dx, room.y + dir.dy)); enter(cell, dir.opposite); }
  function resolve(actor) { rocks.forEach(r => { const dx = actor.x - r.x, dy = actor.y - r.y, len = Math.hypot(dx, dy) || 1, min = actor.r + r.r; if (len < min) { actor.x = r.x + dx / len * min; actor.y = r.y + dy / len * min; } }); }
  function hurt(e, amount) { if (e.dead) return; e.hp -= amount; e.hit = performance.now() + 100; const a = Math.atan2(e.y - player.y, e.x - player.x); e.kx = Math.cos(a) * 260; e.ky = Math.sin(a) * 260; e.knock = performance.now() + 100; fx.push({ type: 'burst', x: e.x, y: e.y, size: 62, frames: sprites.burst, start: performance.now(), end: performance.now() + 260 }); if (e.hp <= 0) { e.dead = true; fx.push({ type: 'burst', x: e.x, y: e.y, size: 110, frames: sprites.burst, start: performance.now(), end: performance.now() + 420 }); if (e.type !== 'boss' && Math.random() < .34) pickups.push({ x: e.x, y: e.y, type: Math.random() < .52 ? 'health' : 'mana', r: 18, bob: Math.random() * Math.PI * 2 }); if (player.harvest) player.hp = Math.min(player.maxHp, player.hp + 5); } }
  function attack() { const now = performance.now(); if (paused || now < player.attackReady) return; if (!player.vip) player.mana = Math.min(player.maxMana, player.mana + player.attackMana); if (player.weapon === 'staff' || player.weapon === 'bow') { const staff = player.weapon === 'staff', effectScale = clamp(player.range / (staff ? 90 : 84), 1, 2.5); player.attackReady = now + (player.vip ? 55 : staff ? 420 : 330); const target = enemies.filter(e => !e.dead).sort((a,b) => d(a,player) - d(b,player))[0]; if (staff && target) player.facing = Math.atan2(target.y - player.y, target.x - player.x); fx.push({ type: 'shot', x: player.x, y: player.y, vx: Math.cos(player.facing) * (staff ? 420 : 590), vy: Math.sin(player.facing) * (staff ? 420 : 590), r: staff ? 11 : 6, damage: player.damage, staff, effectScale, sprite: staff ? sprites.attack.spell : sprites.attack.arrow, sheetFrames: staff ? 4 : 8, start: now, end: now + 1250 }); return; } const sword = player.weapon === 'sword', range = sword ? player.range : player.range * .83, effectScale = clamp(range / (sword ? 108 : 60), 1, 2.5); player.attackReady = now + (player.vip ? 55 : sword ? 360 : 260); fx.push({ type: 'slash', x: player.x, y: player.y, a: player.facing, range, sword, effectScale, sprite: sword ? sprites.attack.slash : sprites.attack.punch, sheetFrames: sword ? 10 : 8, start: now, end: now + 210 }); enemies.forEach(e => { const a = Math.atan2(e.y - player.y, e.x - player.x), delta = Math.atan2(Math.sin(a - player.facing), Math.cos(a - player.facing)); if (Math.abs(delta) < (sword ? 1.22 : .85) && d(e, player) < range + e.r) hurt(e, player.damage); }); }
  function cast() { const now = performance.now(), cost = { brawler: 20, swordsman: 18, mage: 28, ranger: 18 }[player.hero]; if (paused || (!player.vip && (now < player.skillReady || player.mana < cost))) return; player.skillReady = player.vip ? now : now + player.skillCd;
    if (player.hero === 'brawler') { if (!player.vip) player.mana = Math.max(0, player.mana - 20); fx.push({ type: 'slam', x: player.x, y: player.y, r: 155, tick: 0, frames: sprites.burst, start: now, end: now + 700 }); enemies.filter(e => d(e, player) < 155 + e.r).forEach(e => hurt(e, player.damage * 1.75)); }
    if (player.hero === 'swordsman') { if (!player.vip) player.mana = Math.max(0, player.mana - 18); for (let i = -1; i <= 1; i++) { const a = player.facing + i * .2; fx.push({ type: 'crescent', x: player.x, y: player.y, a, vx: Math.cos(a) * 470, vy: Math.sin(a) * 470, r: 25, damage: player.damage * .9, hitIds: [], frames: sprites.vortex, start: now, end: now + 850 }); } }
    if (player.hero === 'mage') { if (!player.vip) player.mana = Math.max(0, player.mana - 28); fx.push({ type: 'storm', x: player.x, y: player.y, r: 165, tick: 0, frames: sprites.vortex, start: now, end: now + 2300 }); }
    if (player.hero === 'ranger') { if (!player.vip) player.mana = Math.max(0, player.mana - 18); for (let i = -4; i <= 4; i++) { const a = player.facing + i * .12; fx.push({ type: 'shot', x: player.x, y: player.y, vx: Math.cos(a) * 620, vy: Math.sin(a) * 620, r: 7, damage: player.damage * .7, pierce: 1, frames: sprites.burst, start: now, end: now + 1050 }); } fx.push({ type: 'volley', x: player.x, y: player.y, a: player.facing, frames: sprites.burst, start: now, end: now + 430 }); }
  }
  function dash() { const now = performance.now(); if (paused || now < player.dashReady) return; player.dashReady = now + player.dashCd; player.dashUntil = now + 145; player.invuln = now + 190; fx.push({ type: 'dash', x: player.x, y: player.y, end: now + 340 }); }
  function offerBoon() { boonPending = true; paused = true; ui.choices.innerHTML = ''; [...boonPool].sort(() => Math.random() - .5).slice(0, 3).forEach(([name, text, apply]) => { const b = document.createElement('button'); b.className = 'boon'; b.innerHTML = `<span class="rarity">月蝕遺物</span><h2>${name}</h2><p>${text}</p><span class="select">選擇力量</span>`; b.onclick = () => { apply(player); paused = false; boonPending = false; ui.boons.classList.remove('show'); }; ui.choices.append(b); }); ui.boons.classList.add('show'); }
  function endRun(victory) { paused = true; runDone = true; ui.resultSub.textContent = victory ? '月蝕已退散' : '遠征失敗'; ui.resultTitle.textContent = victory ? '迷宮已淨化' : '遠征結束'; ui.score.textContent = victory ? '你擊敗了月蝕守衛，完成本次迷宮遠征。' : '整裝後再次挑戰月蝕迷宮。'; ui.gameover.classList.add('show'); }
  function toggleVip() { if (!player) return; player.vip = !player.vip; if (player.vip) { player.hp = player.maxHp; player.mana = player.maxMana; player.skillReady = 0; } updateHUD(); }
  function takeDamage(amount, now, invulnFor) { if (player.vip || now <= player.invuln) return false; player.hp -= amount; player.invuln = now + invulnFor; return true; }
  function updateHUD() { if (!player || !room) return; const state = room.final ? (room.cleared ? '祭壇已淨化' : '月蝕祭壇・Boss') : room.cleared ? '房間已淨化・出口開啟' : `遭遇 ${enemies.filter(e => !e.dead).length} 名敵人`; const cooldown = Math.max(0, player.skillReady - performance.now()); ui.stageStatus.innerHTML = `迷宮 <b>${room.x + 1}-${room.y + 1}</b>　${state}${player.vip ? '　<b>VIP</b>' : ''}`; ui.hp.style.width = `${clamp(player.hp / player.maxHp * 100, 0, 100)}%`; ui.mana.style.width = `${clamp(player.mana / player.maxMana * 100, 0, 100)}%`; ui.skill.style.width = `${player.vip ? 100 : clamp(100 - cooldown / player.skillCd * 100, 0, 100)}%`; ui.skill.style.background = player.vip ? '#ff8d4d' : cooldown ? '#6e6681' : '#f0c967'; ui.hpText.textContent = `${Math.ceil(Math.max(0, player.hp))}/${player.maxHp}`; ui.manaText.textContent = `${Math.floor(player.mana)}/${player.maxMana}`; ui.skillText.textContent = player.vip ? 'VIP・技能無冷卻' : cooldown ? `${player.skillName} ${Math.ceil(cooldown / 1000)} 秒` : `${player.skillName}・E`; ui.weapons.forEach(b => b.setAttribute('aria-pressed', String(b.dataset.weapon === player.weapon))); }
  function update(now, dt) { if (paused || !player) return; const dx = stick.x + (keys.has('d') || keys.has('arrowright') ? 1 : 0) - (keys.has('a') || keys.has('arrowleft') ? 1 : 0), dy = stick.y + (keys.has('s') || keys.has('arrowdown') ? 1 : 0) - (keys.has('w') || keys.has('arrowup') ? 1 : 0), len = Math.hypot(dx, dy); if (len) { const speed = player.speed * (now < player.dashUntil ? 3.25 : 1); player.x += dx / len * speed * dt; player.y += dy / len * speed * dt; resolve(player); } player.mana = player.vip ? player.maxMana : Math.min(player.maxMana, player.mana + player.manaRegen * dt); if (player.vip) player.hp = player.maxHp; const threshold = player.r + 2; if (room.cleared) { if (player.x <= threshold) nextRoom(dirs[3]); else if (player.x >= W - threshold) nextRoom(dirs[1]); else if (player.y <= threshold) nextRoom(dirs[0]); else if (player.y >= H - threshold) nextRoom(dirs[2]); } player.x = clamp(player.x, player.r, W - player.r); player.y = clamp(player.y, player.r, H - player.r); pickups = pickups.filter(p => { if (d(p, player) > p.r + player.r) return true; if (p.type === 'health') player.hp = Math.min(player.maxHp, player.hp + 30); else player.mana = Math.min(player.maxMana, player.mana + 26); fx.push({ type: 'burst', x: p.x, y: p.y, size: 76, frames: sprites.burst, start: now, end: now + 260 }); return false; });
    fx.filter(f => f.type === 'shot').forEach(f => { f.x += f.vx * dt; f.y += f.vy * dt; if (f.staff) { const target = enemies.filter(e => !e.dead).sort((a,b) => d(a,f) - d(b,f))[0]; if (target) { const a = Math.atan2(target.y-f.y,target.x-f.x); f.vx += Math.cos(a)*38; f.vy += Math.sin(a)*38; } } const hit = enemies.find(e => !e.dead && (!f.hitIds || !f.hitIds.includes(e)) && d(e, f) < e.r + f.r); if (hit) { hurt(hit, f.damage); if (f.pierce) { f.pierce--; f.hitIds = [...(f.hitIds || []), hit]; } else f.end = now; } }); fx.filter(f => f.type === 'crescent').forEach(f => { f.x += f.vx * dt; f.y += f.vy * dt; enemies.filter(e => !f.hitIds.includes(e) && d(e, f) < e.r + f.r).forEach(e => { hurt(e, f.damage); f.hitIds.push(e); }); }); fx.filter(f => f.type === 'storm').forEach(f => { f.x = player.x; f.y = player.y; if (now - f.tick > 270) { f.tick = now; enemies.filter(e => d(e, f) < e.r + f.r).forEach(e => hurt(e, player.castDamage * .82)); } }); fx.filter(f => f.type === 'slam').forEach(f => { if (now - f.tick > 180) { f.tick = now; enemies.filter(e => d(e, f) < e.r + f.r).forEach(e => hurt(e, player.damage * .3)); } });
    enemies.forEach(e => { if (e.dead) return; if (now < e.knock) { e.x += e.kx * dt; e.y += e.ky * dt; return; } const distance = d(e,player); if (e.type === 'boss' && now > e.skill) { e.skill = now + 3200; const a = Math.atan2(player.y-e.y, player.x-e.x); for (let i=-2;i<=2;i++) fx.push({ type:'enemyShot', x:e.x,y:e.y,vx:Math.cos(a+i*.18)*330,vy:Math.sin(a+i*.18)*330,r:10,damage:16,end:now+1600 }); } if (e.type === 'ranged' && distance < 255) { if (now > e.ready) { e.ready = now + 1150; const a = Math.atan2(player.y-e.y,player.x-e.x); fx.push({ type:'enemyShot',x:e.x,y:e.y,vx:Math.cos(a)*290,vy:Math.sin(a)*290,r:7,damage:e.damage,end:now+1400 }); } } else if (distance > player.r + e.r + 3) { e.x += (player.x-e.x)/distance*e.speed*dt; e.y += (player.y-e.y)/distance*e.speed*dt; } else takeDamage(e.damage, now, 480); });
    fx.filter(f => f.type === 'enemyShot').forEach(f => { f.x += f.vx*dt; f.y += f.vy*dt; if (d(f,player)<f.r+player.r) { takeDamage(f.damage, now, 400); f.end=now; } }); enemies = enemies.filter(e => !e.dead); fx = fx.filter(f => f.end > now); if (!enemies.length && !room.cleared) { room.cleared = true; clearedAt = now; if (room.final) setTimeout(() => { if (!runDone) endRun(true); }, 400); else setTimeout(() => { if (!boonPending && !runDone) offerBoon(); }, 430); } if (player.hp <= 0) endRun(false); updateHUD(); }
  function gate(x, y, vertical, open) { ctx.save(); ctx.translate(x,y); if (vertical) ctx.rotate(Math.PI/2); ctx.fillStyle = open ? '#4aa99b' : '#7b4656'; ctx.fillRect(-34,-11,68,22); ctx.strokeStyle = open ? '#b1f4d5' : '#d9858b'; ctx.lineWidth = 3; ctx.strokeRect(-34,-11,68,22); ctx.restore(); }
  function drawMap() { const sx=W-154, sy=18, size=30; ctx.fillStyle='#0c0b11d9';ctx.fillRect(sx-10,sy-10,cols*size+20,rows*size+20); maze.forEach(c=>{const x=sx+c.x*size,y=sy+c.y*size;ctx.fillStyle=c.seen?'#3e3649':'#211d29';ctx.fillRect(x,y,size-3,size-3);if(c.final&&c.seen){ctx.fillStyle='#d89859';ctx.fillRect(x+9,y+9,9,9);}if(c===room){ctx.strokeStyle='#72e3cc';ctx.lineWidth=2;ctx.strokeRect(x+2,y+2,size-7,size-7);} Object.entries(c.doors).forEach(([dir,on])=>{if(!on||!c.seen)return;ctx.strokeStyle='#95839b';ctx.lineWidth=2;if(dir==='e')ctx.strokeRect(x+size-4,y+size/2-3,5,6);if(dir==='s')ctx.strokeRect(x+size/2-3,y+size-4,6,5);});}); }
  function draw(now) { ctx.fillStyle='#15151b';ctx.fillRect(0,0,W,H); if (!player || !room) { ctx.fillStyle='#2a2432';ctx.fillRect(0,0,W,H);ctx.fillStyle='#f0d375';ctx.font='bold 30px sans-serif';ctx.textAlign='center';ctx.fillText('月蝕迷宮',W/2,H/2);ctx.textAlign='start';return; } for(let x=0;x<W;x+=roomW){for(let y=0;y<H;y+=roomH){ctx.fillStyle=(x/roomW+y/roomH)%2?'#1b1a22':'#1f1d26';ctx.fillRect(x+2,y+2,roomW-4,roomH-4);}} ctx.strokeStyle='#403947';ctx.lineWidth=15;ctx.strokeRect(0,0,W,H); dirs.forEach(dir=>{if(!room.doors[dir.key])return;const open=room.cleared;if(dir.key==='n')gate(W/2,7,false,open);if(dir.key==='s')gate(W/2,H-7,false,open);if(dir.key==='w')gate(7,H/2,true,open);if(dir.key==='e')gate(W-7,H/2,true,open);}); rocks.forEach(r=>{ctx.beginPath();ctx.arc(r.x,r.y,r.r+5,0,Math.PI*2);ctx.fillStyle='#100e15';ctx.fill();if(sprites.rock.complete)ctx.drawImage(sprites.rock,r.x-r.r,r.y-r.r,r.r*2,r.r*2);}); pickups.forEach(p=>{const y=p.y+Math.sin(now*.006+p.bob)*4, sprite=p.type==='health'?sprites.healthPotion:sprites.manaPotion;ctx.beginPath();ctx.arc(p.x,y,18,0,Math.PI*2);ctx.fillStyle=p.type==='health'?'#e35a6a33':'#5c9eea33';ctx.fill();if(sprite.complete)ctx.drawImage(sprite,p.x-19,y-19,38,38);}); if(room.final&&!room.cleared){ctx.beginPath();ctx.arc(W/2,H/2,105,0,Math.PI*2);ctx.fillStyle='#bf6a4530';ctx.fill();ctx.strokeStyle='#dd9d60';ctx.lineWidth=3;ctx.stroke();}
    fx.forEach(f=>{ const life = f.end - f.start, progress = f.start ? clamp(1 - (f.end - now) / life, 0, 1) : 0, frame = f.frames?.[Math.min(f.frames.length - 1, Math.floor(progress * f.frames.length))]; if(frame?.complete){const size=f.size || (f.type==='storm'?f.r*2.2:f.type==='slam'?f.r*2.1:f.type==='crescent'?78:f.type==='volley'?105:52);ctx.drawImage(frame,f.x-size/2,f.y-size/2,size,size);} if(f.sprite?.complete){const frames=f.sheetFrames, index=Math.min(frames-1,Math.floor(progress*frames)), sourceWidth=f.sprite.width/frames, scale=(f.type==='slash'?(f.sword?2.5:2.25):(f.staff?1.5:1.35))*(f.effectScale||1);ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.type==='slash'?f.a:Math.atan2(f.vy,f.vx));ctx.drawImage(f.sprite,index*sourceWidth,0,sourceWidth,f.sprite.height,-sourceWidth*scale/2,-f.sprite.height*scale/2,sourceWidth*scale,f.sprite.height*scale);ctx.restore();}if(f.type==='cast'||f.type==='storm'||f.type==='slam'){ctx.beginPath();ctx.arc(f.x,f.y,f.r*(f.type==='slam'?1-progress*.15:1),0,Math.PI*2);ctx.fillStyle=f.type==='slam'?'#f6a24d33':f.type==='storm'?'#9674d83b':'#9972c233';ctx.fill();ctx.strokeStyle=f.type==='slam'?'#ffe0a3':'#d8adff';ctx.lineWidth=f.type==='slam'?5:2;ctx.stroke();}if((f.type==='shot'&&!f.sprite)||f.type==='enemyShot'){ctx.beginPath();ctx.arc(f.x,f.y,f.r+(f.staff?4:0),0,Math.PI*2);ctx.fillStyle=f.type==='shot'?(f.staff?'#dfb7ff':'#f1d184'):'#e0788d';ctx.fill();}if(f.type==='crescent'){ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.a);ctx.beginPath();ctx.arc(0,0,34,-1.1,1.1);ctx.strokeStyle='#cdb4ff';ctx.lineWidth=9;ctx.stroke();ctx.strokeStyle='#fff0b3';ctx.lineWidth=2;ctx.stroke();ctx.restore();}if(f.type==='slash'&&!f.sprite){ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.a);ctx.beginPath();ctx.arc(0,0,f.range,-.9,.9);ctx.strokeStyle=f.sword?'#ffe5a7':'#f4b58d';ctx.lineWidth=f.sword?12:18;ctx.stroke();ctx.restore();}});
    enemies.forEach(e=>{const boss=e.type==='boss', skin=e.type==='ranged'?sprites.ranged:sprites.melee;ctx.beginPath();ctx.arc(e.x,e.y,e.r+5,0,Math.PI*2);ctx.fillStyle=boss?'#df914c55':'#c8586a55';ctx.fill();if(skin.complete)ctx.drawImage(skin,e.x-e.r*1.35,e.y-e.r*1.35,e.r*2.7,e.r*2.7);ctx.fillStyle='#281822';ctx.fillRect(e.x-e.r,e.y-e.r-12,e.r*2,5);ctx.fillStyle=boss?'#f3b65f':'#ec8c91';ctx.fillRect(e.x-e.r,e.y-e.r-12,e.r*2*Math.max(0,e.hp/e.maxHp),5);if(boss){ctx.fillStyle='#f4d36f';ctx.font='bold 14px sans-serif';ctx.textAlign='center';ctx.fillText('月蝕守衛',e.x,e.y-e.r-22);ctx.textAlign='start';}}); ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.facing);if(sprites.hero.complete)ctx.drawImage(sprites.hero,-27,-27,54,54);else{ctx.fillStyle='#5bd4c2';ctx.fillRect(-14,-14,28,28);}ctx.strokeStyle='#f4d28a';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(10,0);ctx.lineTo(31,0);ctx.stroke();ctx.restore(); drawMap(); }
  function loop(now) { const dt=Math.min(.05,(now-last)/1000||0);last=now;update(now,dt);draw(now);requestAnimationFrame(loop); }
  window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','j','e','='].includes(k))e.preventDefault();if(!e.repeat&&k==='=')toggleVip();keys.add(k);if(!e.repeat&&k===' ')dash();if(!e.repeat&&k==='j')attack();if(!e.repeat&&k==='e')cast();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));canvas.addEventListener('mousemove',e=>{if(!player)return;const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*W/r.width;mouse.y=(e.clientY-r.top)*H/r.height;player.facing=Math.atan2(mouse.y-player.y,mouse.x-player.x);});canvas.addEventListener('mousedown',attack);
  ui.weapons.forEach(b=>b.onclick=()=>{if(player){player.weapon=b.dataset.weapon;updateHUD();}});document.querySelectorAll('[data-hero]').forEach(b=>b.onclick=()=>{start(b.dataset.hero);ui.heroSelect.classList.remove('show');});document.querySelector('#restart').onclick=()=>{ui.gameover.classList.remove('show');ui.heroSelect.classList.add('show');};ui.pauseButton.onclick=()=>{if(player&&!paused){paused=true;ui.pauseMenu.classList.add('show');}};document.querySelector('#resume').onclick=()=>{ui.pauseMenu.classList.remove('show');paused=false;};document.querySelector('#returnHome').onclick=()=>{ui.pauseMenu.classList.remove('show');ui.heroSelect.classList.add('show');paused=true;};
  const joy=document.querySelector('#joystick'), thumb=document.querySelector('#joystickThumb');function moveStick(e){const r=joy.getBoundingClientRect(),lim=r.width*.3;let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y);if(l>lim){x=x/l*lim;y=y/l*lim;}stick.x=x/lim;stick.y=y/lim;thumb.style.transform=`translate(calc(-50% + ${x}px), calc(-50% + ${y}px))`;};joy.addEventListener('pointerdown',e=>{stick.id=e.pointerId;joy.setPointerCapture(e.pointerId);moveStick(e);});joy.addEventListener('pointermove',e=>{if(e.pointerId===stick.id)moveStick(e);});['pointerup','pointercancel'].forEach(type=>joy.addEventListener(type,()=>{stick.x=stick.y=0;thumb.style.transform='translate(-50%, -50%)';}));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();({attack,cast,dash}[b.dataset.action])();}));requestAnimationFrame(loop);
})();
