const canvas = document.querySelector('#field');
const ctx = canvas.getContext('2d');
const goldEl = document.querySelector('#gold'), waveEl = document.querySelector('#wave'), baseEl = document.querySelector('#base'), notice = document.querySelector('#notice');
const upgradeButton = document.querySelector('#upgrade'), startButton = document.querySelector('#startWave');
const path = [{x:-20,y:120},{x:220,y:120},{x:220,y:280},{x:460,y:280},{x:460,y:100},{x:660,y:100}];
const typeInfo = { arrow:{cost:45,range:118,rate:.55,damage:7,color:'#4c7990'}, cannon:{cost:80,range:92,rate:1.15,damage:20,color:'#b35d4d'} };
let towers,enemies,shots,gold,base,wave,selectedType,selectedTower,waveActive,spawnLeft,spawnTimer,last;
function reset(){towers=[];enemies=[];shots=[];gold=100;base=20;wave=0;selectedType='arrow';selectedTower=null;waveActive=false;spawnLeft=0;spawnTimer=0;document.querySelectorAll('.tower-choice').forEach(b=>b.classList.toggle('active',b.dataset.type==='arrow'));notice.textContent='Choose a tower, then tap open grass.';render()}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function pointAt(progress){let remaining=progress;for(let i=1;i<path.length;i++){let a=path[i-1],b=path[i],len=distance(a,b);if(remaining<=len)return{x:a.x+(b.x-a.x)*remaining/len,y:a.y+(b.y-a.y)*remaining/len};remaining-=len}return path.at(-1)}
function startWave(){if(waveActive)return;wave++;spawnLeft=6+wave*2;spawnTimer=0;waveActive=true;notice.textContent=`Wave ${wave} is approaching.`;startButton.disabled=true;render()}
function spawnEnemy(){const boss=spawnLeft===1&&wave%5===0;enemies.push({progress:0,hp:(boss?90:22)+wave*8,maxHp:(boss?90:22)+wave*8,speed:boss?30:42+wave*2,reward:boss?35:10+wave,type:boss?'boss':'normal'});spawnLeft--}
function update(dt){if(waveActive&&spawnLeft){spawnTimer-=dt;if(spawnTimer<=0){spawnEnemy();spawnTimer=.7}}if(waveActive&&!spawnLeft&&!enemies.length){waveActive=false;gold+=20;notice.textContent=`Wave cleared. +20 gold.`;startButton.disabled=false}enemies.forEach(e=>e.progress+=e.speed*dt);for(let i=enemies.length-1;i>=0;i--)if(enemies[i].progress>1000){base--;enemies.splice(i,1);notice.textContent='An enemy reached your base.';if(base<=0){notice.textContent='Base lost. Restart to defend again.';waveActive=false;startButton.disabled=true}}towers.forEach(t=>{t.cooldown-=dt;if(t.cooldown>0)return;const target=enemies.filter(e=>distance(t,pointAt(e.progress))<t.range).sort((a,b)=>b.progress-a.progress)[0];if(target){shots.push({x:t.x,y:t.y,target,damage:t.damage,type:t.type});t.cooldown=t.rate}});for(let i=shots.length-1;i>=0;i--){const s=shots[i],p=pointAt(s.target.progress),dx=p.x-s.x,dy=p.y-s.y,d=Math.hypot(dx,dy);if(!enemies.includes(s.target)){shots.splice(i,1);continue}if(d<12){hit(s.target,s.damage,s.type==='cannon');shots.splice(i,1)}else{s.x+=dx/d*430*dt;s.y+=dy/d*430*dt}}}
function hit(enemy,damage,splash){const targets=splash?enemies.filter(e=>distance(pointAt(e.progress),pointAt(enemy.progress))<42):[enemy];targets.forEach(e=>e.hp-=damage);for(let i=enemies.length-1;i>=0;i--)if(enemies[i].hp<=0){gold+=enemies[i].reward;enemies.splice(i,1)}}
function gridPos(event){const r=canvas.getBoundingClientRect(),x=(event.clientX-r.left)*640/r.width,y=(event.clientY-r.top)*400/r.height;return{x:Math.floor(x/40)*40+20,y:Math.floor(y/40)*40+20}}
function pathDistance(point,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((point.x-a.x)*dx+(point.y-a.y)*dy)/(dx*dx+dy*dy)));return Math.hypot(point.x-(a.x+dx*t),point.y-(a.y+dy*t))}
function onField(event){if(base<=0)return;const pos=gridPos(event);const tower=towers.find(t=>distance(t,pos)<18);if(tower){selectedTower=tower;upgradeButton.disabled=tower.level>=3||gold<40*tower.level;notice.textContent=`Selected level ${tower.level} ${tower.type} tower.`;render();return}const pointNearPath=path.some((p,i)=>i&&pathDistance(pos,path[i-1],p)<32);if(pointNearPath||towers.some(t=>distance(t,pos)<38)){notice.textContent='Towers need open ground.';return}const info=typeInfo[selectedType];if(gold<info.cost){notice.textContent='Not enough gold.';return}gold-=info.cost;towers.push({...pos,type:selectedType,level:1,range:info.range,rate:info.rate,damage:info.damage,cooldown:.2});notice.textContent=`${selectedType==='arrow'?'Arrow':'Cannon'} tower built.`;render()}
function upgrade(){if(!selectedTower)return;const cost=40*selectedTower.level;if(gold<cost||selectedTower.level>=3)return;gold-=cost;selectedTower.level++;selectedTower.damage+=selectedTower.type==='cannon'?12:5;selectedTower.range+=12;upgradeButton.disabled=selectedTower.level>=3;notice.textContent='Tower upgraded.';render()}
function render(){ctx.fillStyle='#b9dd9b';ctx.fillRect(0,0,640,400);ctx.strokeStyle='rgba(67,112,77,.12)';for(let x=0;x<=640;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,400);ctx.stroke()}for(let y=0;y<=400;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(640,y);ctx.stroke()}ctx.strokeStyle='#c6a777';ctx.lineWidth=31;ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(path[0].x,path[0].y);path.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();ctx.strokeStyle='#e0c695';ctx.lineWidth=20;ctx.stroke();towers.forEach(t=>{ctx.fillStyle=t===selectedTower?'#f4d36c':'#47636c';ctx.beginPath();ctx.arc(t.x,t.y,15,0,Math.PI*2);ctx.fill();ctx.fillStyle=t.type==='cannon'?'#b35d4d':'#4c7990';ctx.fillRect(t.x-6,t.y-18,12,22);ctx.fillStyle='#253a43';ctx.fillRect(t.x+4,t.y-15,18,6);ctx.fillStyle='#fff';ctx.font='10px sans-serif';ctx.textAlign='center';ctx.fillText(t.level,t.x,t.y+4)});enemies.forEach(e=>{const p=pointAt(e.progress);ctx.fillStyle=e.type==='boss'?'#833d65':'#785b96';ctx.beginPath();ctx.arc(p.x,p.y,e.type==='boss'?15:10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4b2d3d';ctx.fillRect(p.x-11,p.y-19,e.type==='boss'?22:20,4);ctx.fillStyle='#eb8079';ctx.fillRect(p.x-11,p.y-19,(e.type==='boss'?22:20)*e.hp/e.maxHp,4)});shots.forEach(s=>{ctx.fillStyle=s.type==='cannon'?'#f2c66b':'#ecf2e5';ctx.beginPath();ctx.arc(s.x,s.y,s.type==='cannon'?5:3,0,Math.PI*2);ctx.fill()});goldEl.textContent=gold;waveEl.textContent=wave;baseEl.textContent=base;upgradeButton.disabled=!selectedTower||selectedTower.level>=3||gold<40*selectedTower.level}
canvas.addEventListener('pointerdown',onField);document.querySelectorAll('.tower-choice').forEach(b=>b.addEventListener('click',()=>{selectedType=b.dataset.type;selectedTower=null;document.querySelectorAll('.tower-choice').forEach(x=>x.classList.toggle('active',x===b));notice.textContent=`${selectedType==='arrow'?'Arrow':'Cannon'} tower selected.`;render()}));upgradeButton.addEventListener('click',upgrade);startButton.addEventListener('click',startWave);document.querySelector('#restart').addEventListener('click',reset);function loop(now){const dt=Math.min(.04,(now-(last||now))/1000);last=now;update(dt);render();requestAnimationFrame(loop)}reset();requestAnimationFrame(loop);
